# SPDX-FileCopyrightText: 2017-2021 Contributors to the OpenSTF project
#
# SPDX-License-Identifier: MPL-2.0
name: Docs Check

# Check docs when directly editing develop or main
# and on pull request
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - "**"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: Checkout code
      uses: actions/checkout@v1
    # Build documentation
    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: |
          cp requirements.txt docs/requirements.txt &&\
          printf "\nsphinx_rtd_theme\n" >> docs/requirements.txt &&\
          sphinx-apidoc -o docs openstf
        docs-folder: "docs/"
